# -*- coding: utf-8 -*-
"""countingsort

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dq7n1VYgGUUBGtub-vogZXHcZDPoyc_M
"""

def countingSort(A) :
    k = max(A)
    C = [0 for _ in range(k + 1)]
    for j in range(len(A)) :
        C[A[j]] += 1
    for i in range(1, k + 1) :
        C[i] += C[i -1]
    B = [0 for _ in range(len(A))]
    for j in range(len(A) - 1, -1, -1) :
        B[C[A[j]] - 1] = A[j]
        C[A[j]] -= 1
    return B