# -*- coding: utf-8 -*-
"""listnode

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qBXd4dS7Y_bTxM6y9FunJ4M5PZhjhzjp
"""

class ListNode :
    def __init__(self, newItem, nextNode : 'ListNode') :
        self.item = newItem
        self.next = nextNode