# -*- coding: utf-8 -*-
"""selectionsort

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TKevnuM_Ppi-etIaLBT36Oge1ZvguRuq
"""

def selectionSort(A) :
    for last in range(len(A) - 1, -1, -1) :
        k = theLargest(A, last)
        A[k], A[last] = A[last], A[k]

def theLargest(A, last:int) -> int :
    largest = 0
    for i in range(last + 1) :
        if A[i] > A[largest] :
            largest = i

    return largest

def bubbleSort(A) :
    for numElements in range(len(A), 0, -1) :
        for i in range(numElements -1) :
            if A[i] > A[i + 1] :
                A[i], A[i + 1] = A[i + 1], A[i]