# -*- coding: utf-8 -*-
"""shellsort

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1p9rwnF4q1246cO2uu_X-zGwCJXu6dicE
"""

def shellSort(A) :
    H = gapSequence(len(A))
    for h in H :
        for k in range(h) :
            stepinsertionSort(A, k, h)

def stepinsertionSort(A, k : int, h : int) :
    for i in range(k + h, len(A), h) :
        j = i - h
        newItem = A[i]
        while 0 <= j and newItem < A[j] :
            A[j + h] = A[j]
            j -= h
        A[j + h] = newItem

def gapSequence(n : int) -> list :
    H = []; gap = 0; i = 0;
    while True :
        gap += 2 ** i
        i += 1
        if gap >= n/2 : break
        H.append(gap)
    H.reverse()
    print(H)
    return H